added option for hook

diff --git a/scripts/lib/build b/scripts/lib/build
--- a/scripts/lib/build
+++ b/scripts/lib/build
@@ -1,26 +1,31 @@
 #!/bin/bash
 
 #build repo
-BUILDER="firstandthird/builder:0.0.10"
+BUILDER="firstandthird/builder:0.0.12"
 docker pull $BUILDER > /dev/null 2>&1
-docker run \
+if [[ "$?" != 0 ]]; then
+  echo "error pulling image"
+  exit 1
+fi
+IMAGE=$(docker run \
   --rm \
   -e USER=$GITHUB_USER \
   -e REPO=$GITHUB_REPO \
   -e BRANCH=$GITHUB_BRANCH \
   -e TOKEN=$GITHUB_TOKEN \
   -e TAG=$DOCKER_TAG \
-  -e DEBUG=1 \
   -e PUSH=1 \
   -e PUSH_LATEST=1 \
   -e REGISTRY=$REGISTRY \
   -e DOCKER_AUTH=$DOCKER_AUTH \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -v /repos:/repos \
-  ${BUILDER}
+  ${BUILDER})
 
 if [[ "$?" != 0 ]]; then
   echo "there was an error building"
+  echo $IMAGE
   #post2slack --tags error --message "$GITHUB_REPO#$GITHUB_BRANCH failed to build $IMAGE"
   exit 1
 fi
+echo $IMAGE
diff --git a/scripts/push/default b/scripts/push/default
--- a/scripts/push/default
+++ b/scripts/push/default
@@ -8,4 +8,22 @@ if [[ -n "$ONLY_BRANCH" && "$ONLY_BRANCH" != "$GITHUB_BRANCH" ]]; then
   echo "looking for $ONLY_BRANCH, got $GITHUB_BRANCH"
   exit 0
 fi
-bash /scripts/lib/build
+IMAGE=$(bash /scripts/lib/build)
+
+if [[ "$?" != 0 ]]; then
+  echo $IMAGE
+  exit
+fi
+
+if [[ -n "$HOOK" ]]; then
+  echo "triggering hook: $HOOK"
+  curl \
+   -H "Content-Type: application/json" \
+   -X POST \
+   -d "{\"repo\":\"$GITHUB_REPO\",\"user\":\"$GITHUB_USER\",\"branch\":\"$GITHUB_BRANCH\",\"dockerImage\":\"$IMAGE\"}" \
+   $HOOK >> /dev/null 2>&1
+
+  if [[ "$?" != 0 ]]; then
+    echo "Hook errored"
+  fi
+fi
